microsoft/gpt-review

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/pull_request_template.md
> chore: Update bug_report.yml

- .vscode/settings.json
- README.md
- src/gpt_review/_ask.py
- tests/conftest.py
- tests/test_gpt_cli.py
Reverts microsoft/gpt-review#5
> Revert "feat: add file param to ask prompt"

- .github/workflows/python.yml
- src/gpt_review/_ask.py
> fix: llama_index calls fail in build

- .github/workflows/python.yml
> ci: Add caching to python steps

- .devcontainer/devcontainer.json
- .vscode/settings.json
- pyproject.toml
> ci: adding Ruff extension and updating configs to dedup code checks

- .github/workflows/python.yml
> ci: update publish to set version

- .github/workflows/python.yml
> ci: Update python.yml

- .github/workflows/python.yml
> ci: Update python.yml to install xdist

- pyproject.toml
> fix: Add min pin for llama_index

- .github/workflows/test-action.yml
> ci: adding capability for A/B Test

- pyproject.toml
> fix: update llama-index

- src/gpt/__main__.py
- src/gpt_review/__main__.py
- tests/test_gpt_cli.py
> fix: enable run via 'python -m gpt' 

- tests/test_gpt_cli.py
> Refactor test_gpt_cli.py and update error messages

- pyproject.toml
- src/gpt_review/_ask.py
- src/gpt_review/_github.py
- tests/conftest.py
- tests/test_github.py
- tests/test_gpt_cli.py
- tests/test_review.py
> refactor: increase github test coverage

- .github/workflows/python.yml
- pyproject.toml
- tests/conftest.py
> test: add implicit unit test marker

- src/gpt_review/_ask.py
- src/gpt_review/_llama_index.py
- tests/test_gpt_cli.py
> fix: add reset and branch params for indexes

- src/gpt_review/_openai.py
This reverts commit 6fd84d837d3e6cc62c1784b8e1441a01001c3bcc.
> chore: Revert "fix: another attempt at rate limit retry (#80)"

- src/gpt_review/_openai.py
- src/gpt_review/context.py
- tests/conftest.py
> fix: Update context.py

- .github/workflows/python.yml
> ci: refactor pipeline tests

- src/gpt_review/_review.py
> fix: improve suggestion text to try and eliminate low quality suggestions 

- src/gpt_review/_openai.py
- src/gpt_review/prompts/prompt_bug.yaml
- src/gpt_review/prompts/prompt_coverage.yaml
- src/gpt_review/prompts/prompt_summary.yaml
> fix: Prompts content shuffled

- src/gpt_review/context.py
> fix: API Type value missing when using key vault 

- .github/checklistConfig.json
- .github/workflows/dynamic-template.yml
> chore: Create dynamic-template.yml
